### ISSUE TITLE
[Bug] NameError: global name 'template' is not defined

### ISSUE THREAD

**Issue by Kristinita** [math2001/BetterSnippetMaker#1]
### 1. Summary

I don't can create snippets via BetterSublimeSnippet. Blank snippets create for me.

### 2. Expected behavior

Successfully snippets creating.

### 3. Actual behavior

```python
Traceback (most recent call last):
  File "BetterSnippetManager in E:\Sublime Text 3\Data\Installed Packages\BetterSnippetMaker.sublime-package", line 99, in make_snippet
NameError: global name 'template' is not defined
```

### 4. Steps to reproduce

The problem is reproduced for me in a version of Sublime Text without plugins and user settings.

`Package Control: Add Repository` → I insert **<https://github.com/math2001/BetterSnippetMaker.git>** → <kbd>Enter</kbd> → `Package Control: Install Package` → I select `BetterSnippetMaker` → I restart Sublime Text.

I select any text, for example,

```shell
\$ErrorActionPreference = 'Stop';

\$packageName= '${1:Paste or print here correct package name}'
\$toolsDir   = "\$(Split-Path -parent \$MyInvocation.MyCommand.Definition)"
\$url        = '${2:Paste here correct download URL.}'
\$url64      = '${3:Paste here correct download URL for 64-bit Windows. If for 32-bit and 64-bit Windows have one installation file, do not write anything here.}'

\$packageArgs = @{
  packageName   = \$packageName
  unzipLocation = \$toolsDir
  url           = \$url
  url64bit      = \$url64

  checksum        = '${4:Paste here correct SHA256 checksum.}'
  checksumType    = 'sha256'
  checksum64      = '${5:Paste here correct SHA256 checksum for 64-bit zip file. If for 32-bit and 64-bit Windows have one installation file, paste here same checksum like in «checksum» section.}'
  checksumType64  = 'sha256'

}

Install-ChocolateyZipPackage @packageArgs
```

→ <kbd>Ctrl+Shift+P</kbd> → `BetterSnippetManager: Create New Snippet` → I print `test` → <kbd>Enter</kbd> → I print `test` → <kbd>Enter</kbd> → I print `source.powershell` → <kbd>Enter</kbd> → I print `Snippets` (really folder) → <kbd>Enter</kbd> → <kbd>Enter</kbd> → I get stack trace, blank snippet was created for me.

### 5. Possibly reason

I think, that problem because of the name of package. Please, define, how you package will be named.

### 6. Environment

**Operating system and version:**
Windows 32-bit 10.0.14393
**Sublime Text:**
Build 3126

Thanks.

**Comment by math2001** [comment]
Fixing this, wait a sec...

**Comment by math2001** [comment]
I pushed new changes, can you try? ~~(if the folder doesn't exist, it won't create it, fixing it now)~~

**Comment by Kristinita** [comment]
Thanks, now test snippets succesfully create for me! And new folders successfully create too.

**Comment by Kristinita** [comment]
But if <kbd>Ctrl+Shift+P</kbd> → `BetterSublimeManager: Edit Settings` → I get popup and error in console:

![SublimeManager](http://i.imgur.com/AwOaYYo.png)

```json
command: edit_settings {"base_file": "${packages}/BetterSnippetManager/BetterSnippetManager.sublime-settings", "default": "// Your settings for BetterSnippetManager. See the default file to see the different options. \n{\n\t$0\n}\n"}
error: The settings file "res://Packages/BetterSnippetManager/BetterSnippetManager.sublime-settings" could not be opened
```

Please, define, your package `Manager` or `Maker`.

Thanks.

**Comment by math2001** [comment]
I'm stupid, as you said:

> Please, define, your package Manager or Maker.

I wasn't consistent with my package name (but couldn't remember where I put `Maker`). So, as you probably guessed, you've installed this package in `Packages/BetterSnippetMaker`, that's why it can't find it. I renamed this repo, you just need to remove this package `Package Control: Remove Package` and the repo (if you've add it to your channel). Just reinstall it, and it should works.

Sorry again...
