### ISSUE TITLE
[Bug] Snippets get out of order

### ISSUE THREAD

**Issue by Kristinita** [math2001/BetterSnippetMaker#2]
### 1. Summary

BetterSnippetManager create incorrect snippets.

### 2. Expected behavior

For example, I select line:

```powershell
\$WhoIsSasha = '${1:Sasha Goddess}'
```

Expected behavior:

```xml
<snippet>
    <content><![CDATA[
\$WhoIsSasha = '${1:Sasha Goddess}'
]]></content>
    <tabTrigger>choco-test</tabTrigger>
    <scope>source.powershell</scope>
    <description>Test</description>
</snippet>
```

### 3. Actual behavior

```xml
<snippet>
    <content><![CDATA[
$WhoIsSasha = 'Sasha Goddess'
]]></content>
    <tabTrigger>choco-test</tabTrigger>
    <scope>source.powershell</scope>
    <description>Test</description>
</snippet>
```

This snippet not will be worked correctly.

### 4. Steps to reproduce

The problem is reproduced for me in a version of Sublime Text without plugins and user settings.

I install BetterSnippetManager → I restart Sublime Text → I select my text → <kbd>Ctrl+Shift+P</kbd> → `BetterSnippetManager: Create New Snippet` → I print snippet parameters → I get actual behavior, not expected behavior.

### 5. Environment

**Operating system and version:**
Windows 32-bit 10.0.14393
**Sublime Text:**
Build 3126
**BetterSnippetManager**
v.2017.01.10.00.29.54

Thanks.

**Comment by math2001** [comment]
Thanks! I really appreciate that you raise an issue each time there's a problem and don't stop using this package! That's really nice of you. 👍 

As you can see, I've pushed a commit solving it.

What I've learned from it: the arg `contents` of the command `open_file` is considered as a snippet, not just plain text (something to mention [here](http://docs.sublimetext.info/en/latest/reference/commands.html)

**Comment by Kristinita** [comment]
I create issue or pull request in [**more than 200 Sublime Text repositories**](https://github.com/search?utf8=%E2%9C%93&q=author%3AKristinita&type=Issues&ref=searchresults) 😺. 

@math2001 , you testing your changes? Problem is reproduced for me in v2017.10.04.38.34. Thanks.

**Comment by math2001** [comment]
> I create issue or pull request in more than 200 Sublime Text repositories 😺.

👍 good job then!

> v2017.10.04.38.34

Who... What's this? I get the `2017` and `10` to match with the last commit's date, that's it... Are you talking about the last commit (72284ab8e0cd27ba3b3b887bbbfc3a15883550e1)?

With what content do you reproduce this? They all work for me:

```
\$WhoIsSasha = '${1:Sasha Goddess}'
```
```
$this \\$ hello world
```
```
this is a $ test $hello \$world
```

**Comment by Kristinita** [comment]
I'm sorry, I do not restart my Sublime Text after last installation BetterSnippetManager. Now problem fixed for me.

Thank you!
