### ISSUE TITLE
[Feature request] SaneSnippets support

### ISSUE THREAD

**Issue by Kristinita** [math2001/BetterSnippetMaker#3]
### 1. Request

It would be nice, if BetterSnippetManager will support creating and editing [**sane-snippets**](https://github.com/bobthecow/sublime-sane-snippets) files.

### 2. Justification

SaneSnippets more convenient for human readability, than default XML-based snippets. See [**example**](https://github.com/bobthecow/sublime-sane-snippets#sanesnippets-for-sublime-text-2) in SaneSnippets repository.

### 3. Desirable behavior

<kbd>Ctrl+Shift+P</kbd> → `BetterSnippetManager: Create SaneSnippet` → I print description, tabTrigger and scope, → I save file with extension `sane-snippet`.

<kbd>Ctrl+Shift+P</kbd> → `BetterSnippetManager: Edit Snippets` → I can select my sane-snippet files.

Thanks.

**Comment by math2001** [comment]
I'm planning on doing that! Just, when I installed SaneSnippet, there was no command "migrate" (from `.sublime-snippet` to `.sane-snippet`). So I wanted to create it myself, and because the code wasn't good for me, I redid the hole thing, and yet I'm not done since I'm doing other stuff (MarkdownCodeBuilder).

So, for sure, it'll be added.

**Comment by Kristinita** [comment]
@math2001 , please, release your changes.

Thanks.

**Comment by math2001** [comment]
Sorry, I forgot about this... Tagged and pushed them.

**Comment by Kristinita** [comment]
@math2001 , thank you!

**Comment by Kristinita** [comment]
@math2001 

> Just, when I installed SaneSnippet, there was no command "migrate" (from .sublime-snippet to .sane-snippet).

Have you ready `.sublime-snippet` to `.sane-snippet` converter?

Thanks.

**Comment by math2001** [comment]
Yep... Checking everything works fine and i'll push it.

**Comment by math2001** [comment]
Alright, I pushed them. So, I guess you'd have to clone this repo in another folder (you should disable the origin `SaneSnippet` while doing this, though). Then, this feature is only available in the menus since it should be run once. `Tools → Packages → SaneSnippets → Migrate From Sublime Snippets to Sane Snippets 👍`

**Comment by Kristinita** [comment]
@math2001 , maybe you create pull request for SaneSnippets? [**My pull-request**](https://github.com/bobthecow/sublime-sane-snippets/pull/11) for this package approved quickly.

And I think, it would be nice add commands to command palette, not only in Menu bar.

Thanks.

**Comment by math2001** [comment]
I'll see about the Pull Request. Indeed, I saw that your PR was quickly accepted.

> And I think, it would be nice add commands to command palette, not only in Menu bar.

For me, the command palette should only present commands that we use often. You don't migrate, clean or regenerate every day, do you? I'm not completely against it, but I'm not sure it's really necessary. Do you feel like you really need it?

**Comment by Kristinita** [comment]
> For me, the command palette should only present commands that we use often.

If I use commands often, I use **shortcuts**. For others, I use command palette. I almost do not use Menu Bar, Context Menu, Tabs Menu and Sidebar menu. For reasons see [**book**](http://nbviewer.jupyter.org/github/Kristinita/SashaBooks/blob/master/IT/Sublime%20Text/Sublime%20Text%20Power%20User.pdf#page=17).

> Do you feel like you really need it?

Dead.

1. I forget the location of the captions that I used seldom in the Menu bar. I need open package source and search, where I can find commands. It takes a time.

See also [**my pull request**](https://github.com/DavidGerva/AddFolderToProject-SublimePlugin/pull/1). User may forgot caption name as well. Thus, good practice — write package name in a caption name. For example, I print in command palette `Sane` → I'll see caption for SaneSnippets → I may find and call to mind a caption name.

2. If user want to run command use Menu Bar, he need `Tools` → `Packages` → `SaneSnippets` → `Migrate From Sublime Snippets to Sane Snippets`. In command palette he need to print `mig` and use fuzzy search for select necessary result. This can save a time.

Thanks.

**Comment by math2001** [comment]
Ok 😄 I'll add it then...

**Comment by Kristinita** [comment]
@math2001 , you don't create a pull request. May I know a reason?

Thanks.

**Comment by math2001** [comment]
Because I was busy. But since it seems to matter a lot for you, I'll do this right now 😄 

Edit: here you go https://github.com/bobthecow/sublime-sane-snippets/pull/12 😋
