### ISSUE TITLE
Setting snipper_folder as Shared Folder

### ISSUE THREAD

**Issue by scottpelak** [math2001/BetterSnippetMaker#4]
I'm having trouble setting the `snippet_folder` to a custom folder not located in `...\Packages\User`.  Ideally, I want to use a shared Folder so my development team and I can all use the same snippets instead of each having a local copy.  Is this supported, and if so, is below valid as the User `.sublime-settings`?   When I use below, Sublime is not finding existing Snippets nor is BetterSnippetManager using the `snippet_folder` as the default path when I create new Snippets via  `BetterSnippetManager: Create New Snippet`.

Example path:  `C:\Shared Folder\Company\Department\Sublime`

Thank you!

BetterSnippetManager.sublime-settings--User
-------------

```
// Your settings for BetterSnippetManager. See the default file to see the different options. 
{
	"snippet_folder" : "C:\\Shared Folder\\Company\\Department\\Snippets\\Sublime"
}

```

**Comment by math2001** [comment]
> When I use below, Sublime is not finding existing Snippets

It won't. Your snippet *have* to be located in the the `Packages` folder at least.
