### ISSUE TITLE
Misspelling in default settings?

### ISSUE THREAD

**Issue by godbout** [math2001/BetterSnippetMaker#5]
I'm using your plugin over others because it's possible to save in a custom folder. Tried to make it work using the "snippet_folder" option I saw in the default settings, but it didn't work. Happened that it should actually be "snippets_folder" instead.

**Comment by mg979** [comment]
I had the same issue, you can also solve it like this

https://gist.github.com/mg979/3b56b570637302b50891f9afd6c2be04

It contains a fix for Edit Snippets (broken if snippets_folder is set to something).

You can also define better which default folder to use (you can always change it when creating snippets).

If you set **_"use_sublime_snippets_folder_as_base_folder": true_** you can have these combinations:

- User/Snippets/(generated from scope)
- User/Snippets
- User/Snippets/Custom

If you set **_"use_sublime_snippets_folder_as_base_folder": false_** you can have these combinations:

- User/Custom
- User/(generated from scope)

**Comment by math2001** [comment]
Sorry guys, stupid mistake. If was fixed with this commit (e311a90) but I didn't tag it. Doing that now... 

The tag `v1.1.1` is online. Just wait for package control to pick it up, and run `Package Control: Update Packages`

**Comment by godbout** [comment]
No worries. I should actually have done a PR. Next time :p
